apiVersion: v1
kind: Namespace
metadata:
  name: nexa-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: nexa-secrets
  namespace: nexa-admin
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_PASSWORD: admin_password
